language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: AFTEVX54TjTbEILhYffNEpCmPHjuBMoi8BS4cdoEPCeASyJwkN6LIscRCkHMFmoazs6kYOeB5MujSWyLv6nNAd0F8qvjtJv1gcNEDFLHy5NW6zALr7szUtuwG46snHPSmTxXzjFbyyFUBMlBEWiHBUFdi816cA74oZGc/MiKEKiY9ps2wK+pPg53p7P4MUcA2hzxvQskkt5a4hgSDTma/WNI95EV7KbaZI79NeaYJMpnXzYVuFGvvQVjlAPs1o2Katj8iUG8oO9DYpm5PKGOYbK4lfuqm2uMW/JtkK5ofDPAr15yb0zAlhTlVRsuC8ZUo3f/cALYYU+Oxx1+/1+AICXaY7E0tbPRFRZBvjwHxS8pbs2fZWLsjy3JsMReSgc3ZHOZwXyuDjgc59UaX+KRDgZeZtubXMevVKtTZMMkJpkQ5S+atGnKq+SC7c5iYSGs+/cnBd+I4LOiP45wV2Neae5AmqcNMa6dCItgpzdyuGgLksBQNGSI6RkXcZYKQD/YMecmXxROC46tO8NBXzX2b0cLIGhOcpBQaaeMSI5YZEVdVyROo7mJBFYmM61qOrxWnJ6ooHYDHTvTr+mQhnbsTcmW12n7oep96WDlt9s4RoqRv2M5vZczcrjRGX5AmLaTwMlHjG+s1f7l9bujZM2ukFJibDWKze6phO6qrqHdorU=
  app: sample-travis-heroku1
  on:
    repo: 4l3x1s/sample-travis-heroku1
