language: node_js
node_js:
- stable
- '6'
- '4'
deploy:
  provider: heroku
  api_key:
    secure: etr+oh2SHKbS1s9E0iP/6fjxTlnP4wSqiw3KJy7r+RLAUIVw4DpeRbrLrhMs+mIvai4LQfBjbLL95MBAj5x3AYyWv3kuU1jiex+MOljyZ3AmxWy1XVz1SWjo8cOldGF7Mq9y/DlJ83XRrFBoDMZxeijIHbAGv9WrJcHqsxidY+YfI6tHcTTn1G+LN7/0jWXUFqwIb/y2+5B5bpxu1VhuMja/CcypopTlRjMqrE39mS7FJ7WGx9LakNwGsNKSW9ghYbU7CdBS1JM6VcJzyicVd3JnVMh75UMwsd1HpE9Ep4D5xs5ZFzO0MdKjCZ0F+1zBQZk2B6PwZFTvYPV/W5ztYvEHqAJNofky8lqc7aPB4Nc5RDYQJh2Qwfp1Ja5CCyWsq/2hX27jvJkeuVyt+1qQe3s1LK+s5P9QZQDr9ZaAK+SMGzpE6XV7EtBxod1tKbZVokE94nK2YPQ7vgXaEzhPTmIpbicqn0YrAb9597IMxwFXt3fzG9KbxaGNv7EuQ3IS4TghIdKT+rQPttNAftr8USXXn1UpbP0gAuWiNuYxMCOTy6t3lulntJ5rndb+K7DXCAFCQd3E2Aji3Uqa8qGToHf/2cJd82vEoL93FJl7R4tpgEAJ3kxCIe8xMtjicSBi8ReGOtUHwEFkvsLUpFdI9ZMyHjhOHiGDfQSNgQFGnaU=
  app: sample-travis-heroku1
  on:
    repo: 4l3x1s/sample-travis-heroku1
