language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: "BOF10YTIzxOhGU1cMKMvi8/YPSNZwDuLs8oKzVRtjflTVipWrMqR/OClX3HpY6jIYrecnFbYo+q9JjDMDA9zTU5FIbEWACB1TJuI61miZd16HQ07cjGZbhOyuzpoYuAhhFueEfAnA19qVbwSM84NrxU9W8JeZh8eDWhhqPqVms4iUcGq2j1oedse6fieF6b8gQi480t+RZ2hzuLyuLagK0XWWSaf0FKfMTg8Mbf1Mu6VmTvJ+eZld6Xp2XC59ilQVuoDbKAwu5gbSVhKrnbQYjUdvvzVDzgLmlT/dI8SDLcudLtV+YMjCD/Y1VH7ab3r99Vxq06PyJ4P7U0+8uyf3FL8tYNRWM8FgUCwPFviLMkEYTM9r9BuSw4SEXv89NR1ywQIxw26v+k9yep+o3nLf1PRD76HISmoVdDZ9+s6v/BhbN9IVAC5qP0KnZ70K4sD/fyL5e20SzbGhnW1bKDR9PFBxB550H1orKKszZS+5VFVLjXTrX4M8W8EZXy2xb+pGoMmMWncUhSWD6kZCYyeyc9x95in8D0NtHYmUXXDXjXu50fkh99fCX4RrI0Xu0oy99dn1qe+dbUzzM4ausEb03BcFUfgkn71tYWpRvAJ5MybjL+QPWgnfur/e6I1MF/THw5loMJGbs6lCgoBG1QUH82G5LEtwEeIsY2cOOckYz0="
  app: nameless-castle-27800
  on:
    repo: 4l3x1s/sample-travis-heroku1
